// Generated by CoffeeScript 1.9.0
(function() {
  var Conversations, Credits, CustomSearch, FixedView, KiwiSlice, Loading, SwitchView, UserPreferences, View, Widget, bindGoToViewButtons, capitalizeFirstLetter, fixedViews, formatTime, getRandom, getURLParam, htmlEntities, initialize, moveArrayElement, preferencesOnlyPage, receiveParcel, renderExtensionHeight, renderedBool, sendParcel, switchViews, tailorRedditAndHNresults_returnHtml, tailorResults, viewElementId, _tailorHNcomment,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  viewElementId = '';

  renderedBool = false;

  preferencesOnlyPage = false;

  initialize = function(popupParcel) {
    var view, viewName;
    console.log('in init');
    if (getURLParam(window.location, 'optionsOnly') !== '') {
      preferencesOnlyPage = true;
      switchViews.userPreferences.render(popupParcel);
      return 0;
    }
    for (viewName in fixedViews) {
      view = fixedViews[viewName];
      view.init(popupParcel);
    }
    if ((popupParcel.view != null) && (switchViews[popupParcel.view] != null)) {
      return switchViews[popupParcel.view].render(popupParcel);
    } else {
      return switchViews.conversations.render(popupParcel);
    }
  };

  Widget = (function() {
    function Widget(_at_name, _at_parentView, _at___renderStates__) {
      this.name = _at_name;
      this.parentView = _at_parentView;
      this.__renderStates__ = _at___renderStates__;
      this.elsToUnbind = [];
      this.totalRenders = 0;
      this.DOMselector = this.parentView.DOMselector + " #" + this.name + "_Widget";
      this.bindAllGoToViewButtons = (function(_this) {
        return function(viewData) {
          var els_goTo_view, viewValue, _results, _viewName;
          console.log('@bindAllGoToViewButtons = (viewData) =>');
          console.log(_this.DOMname);
          _results = [];
          for (_viewName in switchViews) {
            viewValue = switchViews[_viewName];
            console.log(_viewName);
            els_goTo_view = $(_this.DOMselector + ' .goTo_' + _viewName + 'View');
            console.debug(els_goTo_view);
            _this.elsToUnbind.push(els_goTo_view);
            _results.push(bindGoToViewButtons(els_goTo_view, _viewName, viewData));
          }
          return _results;
        };
      })(this);
      this.unbindWidget = (function(_this) {
        return function() {
          var el, _i, _len, _ref;
          _ref = _this.elsToUnbind;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            el = _ref[_i];
            el.unbind();
          }
          return _this.elsToUnbind = [];
        };
      })(this);
      this.render = (function(_this) {
        return function(renderState, popupParcel) {
          _this.totalRenders++;
          _this.unbindWidget(_this.name);
          _this.renderStates[renderState].paint(popupParcel);
          _this.bindAllGoToViewButtons(popupParcel);
          return _this.renderStates[renderState].bind(popupParcel);
        };
      })(this);
      this.renderStates = this.__renderStates__();
      return this;
    }

    return Widget;

  })();

  CustomSearch = (function(_super) {
    __extends(CustomSearch, _super);

    function CustomSearch(_at_name, _at_parentView, _at_widgetOpenBool) {
      this.name = _at_name;
      this.parentView = _at_parentView;
      this.widgetOpenBool = _at_widgetOpenBool;
      this.__renderStates__ = __bind(this.__renderStates__, this);
      console.debug(this.__renderStates__);
      CustomSearch.__super__.constructor.call(this, this.name, this.parentView, this.__renderStates__);
    }

    CustomSearch.prototype.init = function(popupParcel) {
      this.unbindWidget();
      if (this.widgetOpenBool === false) {
        return this.render('collapsed', popupParcel);
      } else {
        return this.render('opened', popupParcel);
      }
    };

    CustomSearch.prototype.__renderStates__ = function() {
      return {
        collapsed: {
          paint: (function(_this) {
            return function(popupParcel) {
              var duplicateFixedHeight, openedCustomSearchHTML;
              openedCustomSearchHTML = '<div class="topSearchBar" style="padding-bottom: 14px;"> <div class="evenlySpacedContainer"> <input class="queryInputOpen" id="customSearchQueryInput" type="text" placeholder=" combined search" /> <button class="btn btn-mini btn-default goTo_userPreferencesView">User Options <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button> </div>';
              if ((popupParcel.kiwi_customSearchResults.queryString != null) && popupParcel.kiwi_customSearchResults.queryString !== '') {
                openedCustomSearchHTML += "<div style='padding-top: 12px;'><a id='openPreviousSearch'>see custom results for '" + popupParcel.kiwi_customSearchResults.queryString + "' </a> &nbsp;&nbsp;&nbsp;&nbsp; <a id='clearPreviousSearch'>clear</a></div>";
              }
              openedCustomSearchHTML += "</div> <div class='notFixed'></div>";
              $(_this.DOMselector).html(openedCustomSearchHTML);
              console.log('console.log @DOMselector + " .topSearchBar"' + _this.DOMselector + " .topSearchBar");
              duplicateFixedHeight = function() {
                var fixedElHeight;
                fixedElHeight = $(_this.DOMselector + " .topSearchBar").outerHeight();
                console.log('console.log fixedElHeight');
                console.log(fixedElHeight);
                if (fixedElHeight === 0) {
                  return setTimeout(function() {
                    return duplicateFixedHeight();
                  }, 80);
                } else {
                  return $(_this.DOMselector + " .notFixed").css({
                    'height': fixedElHeight + "px"
                  });
                }
              };
              return duplicateFixedHeight();
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              var clearPreviousSearch, inputSearchQueryInput, previousSearchLink;
              console.log('bind: (popupParcel) =>');
              inputSearchQueryInput = $("#customSearchQueryInput");
              previousSearchLink = $("#openPreviousSearch");
              clearPreviousSearch = $("#clearPreviousSearch");
              _this.elsToUnbind = _this.elsToUnbind.concat(inputSearchQueryInput, previousSearchLink, clearPreviousSearch);
              previousSearchLink.bind('click', function() {
                return $("#customSearchQueryInput").click();
              });
              clearPreviousSearch.bind('click', function() {
                var parcel;
                parcel = {
                  msg: 'kiwiPP_refreshSearchQuery'
                };
                return sendParcel(parcel);
              });
              return inputSearchQueryInput.bind('click', function() {
                console.log('@widgetOpenBool = true');
                _this.widgetOpenBool = true;
                return _this.render('opened', popupParcel);
              });
            };
          })(this)
        },
        opened: {
          paint: (function(_this) {
            return function(popupParcel) {
              var activeClass, ariaPressedState, customSearchResultsHTML, duplicateFixedHeight, index, openedCustomSearchHTML, queryString, resultsSummaryArray, serviceDisabledAttr, serviceInfoObject, service_PreppedResults, tagActiveChecked, tagDisabledAttr, tagName, tagObject, _i, _j, _len, _len1, _ref, _ref1, _ref2;
              console.log('popupParcel.kiwi_servicesInfo.length');
              console.log(popupParcel.kiwi_servicesInfo.length);
              queryString = popupParcel.kiwi_customSearchResults.queryString != null ? popupParcel.kiwi_customSearchResults.queryString : '';
              openedCustomSearchHTML = '<div class="topSearchBar"> <div class="evenlySpacedContainer"> <input id="customSearchQueryInput" value="' + queryString + '" type="text" placeholder=" combined search" style="width:234px; margin-right: 10px;" /> <button  class="btn btn-mini btn-default" id="customSearchQuerySubmit" style="margin-right: 10px;">Submit</button> <button style="" class="goTo_userPreferencesView btn btn-mini btn-default"> Options <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button> </div> <br> <div class="evenlySpacedContainer" style="position: relative; top: -8px; margin-bottom: 3px;">';
              _ref = popupParcel.kiwi_servicesInfo;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                serviceInfoObject = _ref[_i];
                openedCustomSearchHTML += '<div>';
                console.log('asdfasdf ' + serviceInfoObject.name);
                console.debug(serviceInfoObject);
                if (serviceInfoObject.active === 'off') {
                  serviceDisabledAttr = ' disabled title="Service must be active, can be changed in options." ';
                } else {
                  serviceDisabledAttr = ' ';
                }
                if ((popupParcel.kiwi_customSearchResults.servicesSearchesRequested != null) && (popupParcel.kiwi_customSearchResults.servicesSearchesRequested[serviceInfoObject.name] != null)) {
                  activeClass = ' active ';
                  ariaPressedState = 'true';
                } else if (popupParcel.kiwi_customSearchResults.servicesSearchesRequested == null) {
                  activeClass = serviceInfoObject.active === 'off' ? ' ' : ' active ';
                  ariaPressedState = serviceInfoObject.active === 'off' ? 'false' : 'true';
                } else {
                  activeClass = ' ';
                  ariaPressedState = 'false';
                }
                if ((serviceInfoObject.customSearchTags != null) && Object.keys(serviceInfoObject.customSearchTags).length > 0) {
                  openedCustomSearchHTML += '<div class="btn-group"> <button data-toggle="button" aria-pressed="' + ariaPressedState + '" autocomplete="off" ' + serviceDisabledAttr + 'class="servicesToSearch btn btn-default btn-mini dropdownLabel ' + activeClass + '" data-serviceName="' + serviceInfoObject.name + '">' + serviceInfoObject.title + '</button> <button ' + serviceDisabledAttr + ' data-toggle="dropdown" class="btn btn-default dropdown-toggle ' + activeClass + 'dropDownPrefs_' + serviceInfoObject.name + '" data-placeholder="false"><span class="caret"></span></button> <ul class="dropdown-menu">';
                  _ref1 = serviceInfoObject.customSearchTags;
                  for (tagName in _ref1) {
                    tagObject = _ref1[tagName];
                    if ((popupParcel.kiwi_customSearchResults.servicesSearchesRequested != null) && (popupParcel.kiwi_customSearchResults.servicesSearchesRequested[serviceInfoObject.name] != null)) {
                      if (popupParcel.kiwi_customSearchResults.servicesSearchesRequested[serviceInfoObject.name].customSearchTags[tagName] != null) {
                        tagActiveChecked = ' checked ';
                      } else {
                        tagActiveChecked = '';
                      }
                    } else {
                      tagActiveChecked = tagObject.include === true ? ' checked ' : '';
                    }
                    tagDisabledAttr = serviceInfoObject.active === 'off' ? ' disabled title="Service must be active, can be changed in options." ' : '';
                    openedCustomSearchHTML += '<li><input ' + tagActiveChecked + tagDisabledAttr + ' type="checkbox" value="' + tagName + '" class="tagPref tagPref_' + serviceInfoObject.name + '" id="' + serviceInfoObject.name + tagName + '"> <label for="' + serviceInfoObject.name + tagName + '">' + tagObject.title + '</label></li>';
                  }
                  openedCustomSearchHTML += '</ul></div>';
                } else {
                  openedCustomSearchHTML += '<button data-toggle="button" aria-pressed="' + ariaPressedState + '" autocomplete="off" type="button" class="servicesToSearch btn btn-mini btn-default  ' + activeClass + '" data-serviceName="' + serviceInfoObject.name + '">' + serviceInfoObject.title + '</button>';
                }
                openedCustomSearchHTML += '</div>';
              }
              openedCustomSearchHTML += '<div> <button aria-pressed="false" autocomplete="off" type="button" class="btn btn-mini btn-default" id="close__' + _this.name + '" > close <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </button> </div> </div>';
              openedCustomSearchHTML += '</div> <div class="notFixed"></div> <div id="customSearchResults"></div>';
              resultsSummaryArray = [];
              customSearchResultsHTML = "";
              if ((popupParcel.kiwi_customSearchResults != null) && (popupParcel.kiwi_customSearchResults.queryString != null) && popupParcel.kiwi_customSearchResults.queryString !== '') {
                _ref2 = popupParcel.kiwi_servicesInfo;
                for (index = _j = 0, _len1 = _ref2.length; _j < _len1; index = ++_j) {
                  serviceInfoObject = _ref2[index];
                  if (popupParcel.kiwi_customSearchResults.servicesSearched[serviceInfoObject.name] != null) {
                    service_PreppedResults = popupParcel.kiwi_customSearchResults.servicesSearched[serviceInfoObject.name].results;
                    resultsSummaryArray.push("<a class='jumpTo' data-serviceindex='" + index + "'>" + serviceInfoObject.title + " (" + service_PreppedResults.length + ")</a>");
                    customSearchResultsHTML += tailorResults[serviceInfoObject.name](serviceInfoObject, service_PreppedResults, popupParcel.kiwi_userPreferences);
                    if (service_PreppedResults.length > 14) {
                      customSearchResultsHTML += '<div class="listing showHidden" data-servicename="' + serviceInfoObject.name + '"> show remaining ' + (service_PreppedResults.length - 11) + ' results</div>';
                    }
                  } else {
                    customSearchResultsHTML += '<br>No results for ' + serviceInfoObject.title + '<br>';
                  }
                }
              } else {
                customSearchResultsHTML += '<div id="customSearchResultsDrop"><br>No results to show... make a search! :) </div><br>';
              }
              customSearchResultsHTML = "<div style='width: 100%; text-align: center;'>" + resultsSummaryArray.join(" - ") + "</div>" + customSearchResultsHTML;
              customSearchResultsHTML += "<br>";
              $(_this.DOMselector).html(openedCustomSearchHTML);
              $(_this.DOMselector + " #customSearchResults").html(customSearchResultsHTML);
              $(_this.DOMselector + " .hidden_listing").hide();
              duplicateFixedHeight = function() {
                var fixedElHeight, fixedElTableHeight;
                fixedElHeight = $(_this.DOMselector + " .topSearchBar").outerHeight();
                fixedElTableHeight = $(_this.DOMselector + " .topSearchBar table").outerHeight();
                console.log('console.log fixedElHeight');
                console.log(fixedElHeight);
                if (fixedElTableHeight === 0) {
                  return setTimeout(function() {
                    return duplicateFixedHeight();
                  }, 80);
                } else {
                  return $(_this.DOMselector + " .notFixed").css({
                    'height': fixedElHeight + "px"
                  });
                }
              };
              return duplicateFixedHeight();
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              var closeWidget, customSearchQueryInput, customSearchQuerySubmit, customSearch_sortByPref, elsServicesActivePrefs, elsServicesButtons, jumpToServiceCustomResults, modifySearch, sendSearch, showHidden;
              customSearchQueryInput = $(_this.DOMselector + " #customSearchQueryInput");
              customSearchQuerySubmit = $(_this.DOMselector + " #customSearchQuerySubmit");
              closeWidget = $(_this.DOMselector + ' #close__' + _this.name);
              customSearch_sortByPref = $(_this.DOMselector + " .conversations_sortByPref");
              modifySearch = $(_this.DOMselector + " .customSearchOpen");
              elsServicesButtons = $(_this.DOMselector + " button.servicesToSearch ");
              elsServicesActivePrefs = $(_this.DOMselector + " .customSearchServicePref input");
              showHidden = $(_this.DOMselector + " .showHidden");
              jumpToServiceCustomResults = $("#customSearchResults .jumpTo");
              _this.elsToUnbind = _this.elsToUnbind.concat(customSearchQueryInput, closeWidget, customSearchQuerySubmit, elsServicesButtons, customSearch_sortByPref, showHidden, jumpToServiceCustomResults, modifySearch);
              modifySearch.bind('click', function() {
                return $("#customSearchQueryInput").focus();
              });
              jumpToServiceCustomResults.bind('click', function(ev) {
                var offsetBy, pxFromTop, serviceIndex;
                serviceIndex = parseInt($(ev.target).data('serviceindex'));
                pxFromTop = $($("#customSearchResults .serviceResultsHeaderBar")[serviceIndex]).offset().top;
                offsetBy = $($("#customSearchResults .serviceResultsHeaderBar")[serviceIndex]).outerHeight() + 40;
                return $('body').scrollTop(pxFromTop - offsetBy);
              });
              showHidden.bind('click', function(ev) {
                var serviceName;
                console.log("showHidden.bind 'click', (ev) ->");
                console.debug(ev);
                serviceName = $(ev.target).data('servicename');
                console.log(_this.DOMselector + " .resultsBox__" + serviceName + " .hidden_listing");
                $(_this.DOMselector + " .resultsBox__" + serviceName + " .hidden_listing").show(1200);
                return $(ev.target).remove();
              });
              elsServicesButtons.bind('click', function(ev) {
                var ariaPressed, serviceName;
                if ($(ev.target).hasClass("dropdownLabel")) {
                  serviceName = $(ev.target).attr('data-serviceName');
                  console.log(serviceName);
                  console.debug($(ev.target).attr('aria-pressed'));
                  ariaPressed = $(ev.target).attr('aria-pressed');
                  if (ariaPressed === 'true') {
                    $('button.dropDownPrefs_' + serviceName).removeClass('active');
                    console.log('if ev.target.checked == "false" ' + serviceName);
                    $(_this.DOMselector + " input.tagPref_" + serviceName).attr('disabled', 'disabled');
                  } else {
                    $('button.dropDownPrefs_' + serviceName).addClass('active');
                    console.log($(ev.target).attr('aria-pressed') + "asdfasdf");
                    $(_this.DOMselector + " input.tagPref_" + serviceName).removeAttr('disabled');
                  }
                }
                return $(ev.target).blur();
              });
              customSearch_sortByPref.bind('change', function(ev) {
                var parcel;
                console.log(' customSearch_sortByPref.val()');
                popupParcel.kiwi_userPreferences.sortByPref = $(ev.target).val();
                parcel = {
                  refreshView: 'conversations',
                  keyName: 'kiwi_userPreferences',
                  newValue: popupParcel.kiwi_userPreferences,
                  localOrSync: 'sync',
                  msg: 'kiwiPP_post_save_a_la_carte'
                };
                return sendParcel(parcel);
              });
              sendSearch = function() {
                var el, elTagPref, elTagPrefs, elsServicesToSearch, parcel, queryString, serviceName, servicesToSearch, tagName, _i, _j, _len, _len1;
                queryString = customSearchQueryInput.val();
                elsServicesToSearch = $(_this.DOMselector + ' button.servicesToSearch[aria-pressed="true"]');
                servicesToSearch = {};
                for (_i = 0, _len = elsServicesToSearch.length; _i < _len; _i++) {
                  el = elsServicesToSearch[_i];
                  serviceName = $(el).attr('data-serviceName');
                  servicesToSearch[serviceName] = {};
                  servicesToSearch[serviceName].customSearchTags = {};
                  elTagPrefs = $(_this.DOMselector + " input.tagPref_" + serviceName + ":checked");
                  for (_j = 0, _len1 = elTagPrefs.length; _j < _len1; _j++) {
                    elTagPref = elTagPrefs[_j];
                    tagName = $(elTagPref).val();
                    servicesToSearch[serviceName].customSearchTags[tagName] = {};
                  }
                }
                console.log('asfdasdfasdf ' + serviceName);
                console.debug(servicesToSearch);
                if (queryString !== '') {
                  parcel = {
                    msg: 'kiwiPP_post_customSearch',
                    customSearchRequest: {
                      queryString: queryString,
                      servicesToSearch: servicesToSearch
                    }
                  };
                  return sendParcel(parcel);
                }
              };
              customSearchQueryInput.keypress(function(event) {
                if (event.charCode === 13) {
                  return sendSearch();
                }
              });
              customSearchQuerySubmit.bind('click', function() {
                return sendSearch();
              });
              closeWidget.bind('click', function() {
                _this.widgetOpenBool = false;
                return _this.render('collapsed', popupParcel);
              });
              return customSearchQueryInput.focus();
            };
          })(this)
        }
      };
    };

    return CustomSearch;

  })(Widget);

  View = (function() {
    function View(_at_name, _at___renderStates__) {
      this.name = _at_name;
      this.__renderStates__ = _at___renderStates__;
      this.render = __bind(this.render, this);
      this.unbindView = __bind(this.unbindView, this);
      this.elsToUnbind = [];
      this.totalRenders = 0;
      this.DOMselector = "#" + this.name + "_View";
      this.Widgets = {};
      this.bindAllGoToViewButtons = (function(_this) {
        return function(viewData) {
          var els_goTo_view, viewValue, _results, _viewName;
          _results = [];
          for (_viewName in switchViews) {
            viewValue = switchViews[_viewName];
            els_goTo_view = $(_this.DOMselector + ' .goTo_' + _viewName + 'View');
            _this.elsToUnbind.push(els_goTo_view);
            _results.push(bindGoToViewButtons(els_goTo_view, _viewName, viewData));
          }
          return _results;
        };
      })(this);
      this.renderStates = this.__renderStates__();
      return this;
    }

    View.prototype.unbindView = function() {
      var el, widget, _i, _j, _len, _len1, _ref, _ref1, _results;
      console.log('unbinding view');
      console.debug(this.elsToUnbind);
      _ref = this.elsToUnbind;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        el = _ref[_i];
        el.unbind();
      }
      this.elsToUnbind = [];
      _ref1 = this.Widgets;
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        widget = _ref1[_j];
        _results.push(widget.unbindWidget());
      }
      return _results;
    };

    View.prototype.render = function(popupParcel, renderState) {
      if (renderState == null) {
        renderState = "__normal__";
      }
      this.totalRenders++;
      this.unbindView(this.name);
      if ((renderState == null) && (this.renderStates.__normal__ == null)) {
        console.log('ERROR: must declare renderState for view ' + this.name + ' since __normal__ undefined');
      }
      console.log('console.debug renderState ' + this.name + renderState);
      console.log(this.totalRenders);
      console.debug(this.renderStates);
      this.renderStates[renderState].paint(popupParcel);
      this.bindAllGoToViewButtons(popupParcel);
      return this.renderStates[renderState].bind(popupParcel);
    };

    return View;

  })();

  FixedView = (function(_super) {
    __extends(FixedView, _super);

    function FixedView(_at_name, _at___renderStates__, uniqueSelectorPostfix) {
      this.name = _at_name;
      this.__renderStates__ = _at___renderStates__;
      FixedView.__super__.constructor.call(this, this.name, this.__renderStates__);
      this.DOMselector += uniqueSelectorPostfix;
      console.log(this.DOMselector);
    }

    return FixedView;

  })(View);

  SwitchView = (function(_super) {
    __extends(SwitchView, _super);

    function SwitchView(_at_name, _at___renderStates__) {
      this.name = _at_name;
      this.__renderStates__ = _at___renderStates__;
      this.render = __bind(this.render, this);
      this.showView = __bind(this.showView, this);
      SwitchView.__super__.constructor.call(this, this.name, this.__renderStates__);
    }

    SwitchView.prototype.showView = function() {
      var viewValue, _results, _viewName;
      _results = [];
      for (_viewName in switchViews) {
        viewValue = switchViews[_viewName];
        if (_viewName === this.name) {
          console.log('showing ' + _viewName);
          _results.push($('#' + _viewName + '_View').css({
            'display': 'block'
          }));
        } else {
          console.log('hiding ' + _viewName);
          _results.push($('#' + _viewName + '_View').css({
            'display': 'none'
          }));
        }
      }
      return _results;
    };

    SwitchView.prototype.render = function(popupParcel, renderState) {
      if (renderState == null) {
        renderState = "__normal__";
      }
      SwitchView.__super__.render.call(this, popupParcel, renderState);
      return this.showView();
    };

    return SwitchView;

  })(View);

  Conversations = (function(_super) {
    __extends(Conversations, _super);

    function Conversations(_at_name) {
      this.name = _at_name;
      this.__renderStates__ = __bind(this.__renderStates__, this);
      Conversations.__super__.constructor.call(this, this.name, this.__renderStates__);
      this.Widgets = {
        customSearch: new CustomSearch('customSearch', this, false)
      };
    }

    Conversations.prototype.init = function(popupParcel) {
      this.unbindWidget();
      return this.render(popupParcel);
    };

    Conversations.prototype.__renderStates__ = function() {
      return {
        __normal__: {
          paint: (function(_this) {
            return function(popupParcel) {
              var index, preppedHTMLstring, researchModeDisabledButtonsHTML, resultsHTML, resultsSummaryArray, serviceInfoObject, service_PreppedResults, submitTitle, submitUrl, totalResults, _i, _len, _ref;
              console.log(' in conversations view');
              console.debug(popupParcel);
              _this.Widgets['customSearch'].init(popupParcel);
              researchModeDisabledButtonsHTML = '';
              if (popupParcel.urlBlocked === true || popupParcel.kiwi_userPreferences.researchModeOnOff === 'off' || ((popupParcel.oldUrl != null) && popupParcel.oldUrl === true)) {
                researchModeDisabledButtonsHTML += "<br> <div style='width:100%;text-align: center;'><button class='btn btn-success' style='font-size: 1.1em;display: inline-block;' id='researchUrlOverride'>Research this Url</button></div> <br>";
              }
              if (popupParcel.kiwi_userPreferences.researchModeOnOff === 'off') {
                researchModeDisabledButtonsHTML += "<br>Research Mode is off <button class='goTo_userPreferencesView btn btn-mini btn-default'> change settings </button><br>";
              }
              $("#researchModeDisabledButtons").html(researchModeDisabledButtonsHTML);
              preppedHTMLstring = '<h3 style="position:relative; top:-10px;">Results for this URL:</h3>';
              resultsSummaryArray = [];
              resultsHTML = "";
              totalResults = 0;
              _ref = popupParcel.kiwi_servicesInfo;
              for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
                serviceInfoObject = _ref[index];
                if ((popupParcel.allPreppedResults[serviceInfoObject.name] != null) && popupParcel.allPreppedResults[serviceInfoObject.name].service_PreppedResults.length > 0) {
                  service_PreppedResults = popupParcel.allPreppedResults[serviceInfoObject.name].service_PreppedResults;
                  totalResults += service_PreppedResults.length;
                  resultsSummaryArray.push("<a class='jumpTo' data-serviceindex='" + index + "'>" + serviceInfoObject.title + " (" + service_PreppedResults.length + ")</a>");
                  resultsHTML += tailorResults[serviceInfoObject.name](serviceInfoObject, service_PreppedResults, popupParcel.kiwi_userPreferences);
                  if (service_PreppedResults.length > 14) {
                    resultsHTML += '<div class="listing showHidden" data-servicename="' + serviceInfoObject.name + '"> show remaining ' + (service_PreppedResults.length - 11) + ' results</div>';
                  }
                } else {
                  if (serviceInfoObject.submitTitle != null) {
                    submitUrl = serviceInfoObject.submitUrl;
                    submitTitle = serviceInfoObject.submitTitle;
                    resultsHTML += '<div>No matches for conversations on ' + serviceInfoObject.title + '... <br> &nbsp;&nbsp;&nbsp;<a target="_blank" href="' + submitUrl + '">' + submitTitle + '</a></div><br>';
                  } else {
                    resultsHTML += '<div>No results for ' + serviceInfoObject.title + '</div>';
                  }
                }
              }
              preppedHTMLstring += "<div style='width: 100%; text-align: center;'>" + resultsSummaryArray.join(" - ") + "</div><br>";
              preppedHTMLstring += resultsHTML;
              $("#resultsByService").html(preppedHTMLstring);
              $(_this.DOMselector + " .hidden_listing").hide();
              console.log('console.log $("#resultsByService").outerHeight()');
              console.log($("#resultsByService").outerHeight());
              if (totalResults < 4 && _this.totalRenders < 2) {
                fixedViews.kiwiSlice.render(popupParcel, "open");
              }
              setTimeout(function() {
                $($('input')[0]).blur();
                $($('a')[0]).blur();
                return $($('button')[0]).blur();
              }, 300);
              $($('input')[0]).blur();
              $($('a')[0]).blur();
              return $($('button')[0]).blur();
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              var conversations_sortByPref, customSearchOpen, jumpToService, researchUrlOverrideButton, showHidden;
              showHidden = $(_this.DOMselector + " .showHidden");
              researchUrlOverrideButton = $(_this.DOMselector + " #researchUrlOverride");
              conversations_sortByPref = $(_this.DOMselector + " .conversations_sortByPref");
              customSearchOpen = $(_this.DOMselector + " .customSearchOpen");
              jumpToService = $("#resultsByService .jumpTo");
              _this.elsToUnbind = _this.elsToUnbind.concat(conversations_sortByPref, showHidden, researchUrlOverrideButton, customSearchOpen, jumpToService);
              jumpToService.bind('click', function(ev) {
                var offsetBy, pxFromTop, serviceIndex;
                serviceIndex = parseInt($(ev.target).data('serviceindex'));
                console.log(serviceIndex);
                pxFromTop = $($("#resultsByService .serviceResultsHeaderBar")[serviceIndex]).offset().top;
                offsetBy = $($("#resultsByService .serviceResultsHeaderBar")[serviceIndex]).outerHeight() + 40;
                return $('body').scrollTop(pxFromTop - offsetBy);
              });
              customSearchOpen.bind('click', function() {
                return $("#customSearchQueryInput").click();
              });
              researchUrlOverrideButton.bind('click', function() {
                var parcel;
                parcel = {
                  msg: 'kiwiPP_researchUrlOverrideButton'
                };
                return sendParcel(parcel);
              });
              showHidden.bind('click', function(ev) {
                var serviceName;
                console.log("showHidden.bind 'click', (ev) -> ");
                console.debug(ev);
                serviceName = $(ev.target).data('servicename');
                $(_this.DOMselector + " .resultsBox__" + serviceName + " .hidden_listing").show(1200);
                return $(ev.target).remove();
              });
              return conversations_sortByPref.bind('change', function(ev) {
                var parcel;
                console.log("'conversations_sortByPref.bind 'change', (ev) ->");
                console.log($(ev.target).val());
                popupParcel.kiwi_userPreferences.sortByPref = $(ev.target).val();
                parcel = {
                  refreshView: 'conversations',
                  keyName: 'kiwi_userPreferences',
                  newValue: popupParcel.kiwi_userPreferences,
                  localOrSync: 'sync',
                  msg: 'kiwiPP_post_save_a_la_carte'
                };
                return sendParcel(parcel);
              });
            };
          })(this)
        }
      };
    };

    return Conversations;

  })(SwitchView);

  UserPreferences = (function(_super) {
    __extends(UserPreferences, _super);

    function UserPreferences(_at_name) {
      this.name = _at_name;
      this.__renderStates__ = __bind(this.__renderStates__, this);
      UserPreferences.__super__.constructor.call(this, this.name, this.__renderStates__);
    }

    UserPreferences.prototype.init = function(popupParcel) {
      this.unbindWidget();
      return this.render(popupParcel);
    };

    UserPreferences.prototype.__renderStates__ = function() {
      return {
        __normal__: {
          paint: (function(_this) {
            return function(popupParcel) {
              var activeCheck, autoOffTimerType, autoOffTimerValue, currentTime, index, notActiveCheck, researchModeExpirationString, researchModeHtml, researchOffString, researchOnString, service, servicesHtml, _i, _len, _ref;
              $(_this.DOMselector + " .userErrMsg").html('');
              console.log('paint: adsfaeaewfawefawefawef(popupParcel) =># viewName = ');
              if (preferencesOnlyPage === true) {
                $("#menuBar_preferences").hide();
              }
              currentTime = Date.now();
              if (popupParcel.kiwi_userPreferences.researchModeOnOff === "off") {
                $("#autoOffTimer").html("Research mode is off, so auto-off timer is not set");
              } else if ((popupParcel.kiwi_userPreferences.autoOffAtUTCmilliTimestamp != null) && popupParcel.kiwi_userPreferences.autoOffAtUTCmilliTimestamp > currentTime) {
                $("#autoOffTimer").html("Auto-Off timer expires at: " + formatTime(popupParcel.kiwi_userPreferences.autoOffAtUTCmilliTimestamp) + "<br>");
              } else if (popupParcel.kiwi_userPreferences.researchModeOnOff === 'off' && (popupParcel.kiwi_userPreferences.autoOffAtUTCmilliTimestamp != null)) {
                $("#autoOffTimer").html("Auto-off timer last expired at: " + formatTime(popupParcel.kiwi_userPreferences.autoOffAtUTCmilliTimestamp) + "<br>");
              } else {
                $("#autoOffTimer").html("Auto-off timer is not set");
              }
              researchModeHtml = '';
              if (popupParcel.kiwi_userPreferences.researchModeOnOff === "on") {
                researchOnString = " checked='checked' ";
                researchOffString = "";
              } else {
                researchOnString = "";
                researchOffString = " checked='checked' ";
              }
              if (typeof autoOffAtUTCmilliTimestamp !== "undefined" && autoOffAtUTCmilliTimestamp !== null) {
                researchModeExpirationString = '<br>Research Mode will turn off (expire) at: ' + formatTime(autoOffAtUTCmilliTimestamp);
                researchModeExpirationString += '<br><button class="btn btn-mini btn-default" id="resetAutoOffTimer">Reset auto-off timer</button>';
              } else {
                researchModeExpirationString = '';
              }
              autoOffTimerType = popupParcel.kiwi_userPreferences.autoOffTimerType;
              autoOffTimerValue = popupParcel.kiwi_userPreferences.autoOffTimerValue;
              var auto20, auto60, autoAlways, autoCustom, autoCustomValue = '';
        if(autoOffTimerType != null){
          if(autoOffTimerType == "20"){ auto20 = " checked='checked' " }
          else if(autoOffTimerType == "60"){ auto60 = " checked='checked' " }
          else if(autoOffTimerType == "always"){ autoAlways = " checked='checked' " }
          else if(autoOffTimerType == "custom"){ autoCustom = " checked='checked' "; autoCustomValue = autoOffTimerValue;}
        };
              researchModeHtml += 'Research Mode: on <input type="radio" name="research" value="on" ' + researchOnString + '> - off <input type="radio" name="research" value="off" ' + researchOffString + '>' + researchModeExpirationString + '<br> <br>Auto-Off in: <br>&nbsp; &nbsp;<label><input type="radio" name="researchAutoOffType" ' + auto20 + ' value="20"> 20 min</label> <br>&nbsp; &nbsp;<label><input type="radio" name="researchAutoOffType" ' + auto60 + ' value="60"> 1 hr</label> <br>&nbsp; &nbsp;<label><input type="radio" name="researchAutoOffType" ' + autoAlways + ' value="always"> Always On</label> <br>&nbsp; &nbsp;<label><input type="radio" name="researchAutoOffType" ' + autoCustom + ' value="custom"> Custom</label> &nbsp; &nbsp; <input id="autoCustomValue" type="text" value="' + autoCustomValue + '" size="4" disabled /> minutes';
              $("#researchModeDrop").html(researchModeHtml);
              servicesHtml = '';
              _ref = popupParcel.kiwi_servicesInfo;
              for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
                service = _ref[index];
                if (service.active === "on") {
                  activeCheck = " checked='checked' ";
                  notActiveCheck = "";
                } else {
                  activeCheck = "";
                  notActiveCheck = " checked='checked' ";
                }
                servicesHtml += '<br> <div class="serviceListing listing"> <table><tbody><tr> <td class="upDownButtons">';
                if (index !== 0) {
                  servicesHtml += '<span class="glyphicon glyphicon-chevron-up" id="' + service.name + '_moveServiceUp" aria-hidden="true"></span>';
                }
                if (index !== 0 && index !== popupParcel.kiwi_servicesInfo.length - 1) {
                  servicesHtml += '<br><br>';
                }
                if (index !== popupParcel.kiwi_servicesInfo.length - 1) {
                  servicesHtml += '<span class="glyphicon glyphicon-chevron-down" id="' + service.name + '_moveServiceDown" aria-hidden="true"></span>';
                }
                servicesHtml += '</td> <td class="serviceInfo">' + service.title + ' - using: <a href="' + service.broughtToYouByURL + '">' + service.broughtToYouByTitle + '</a><br> <div style="padding-left:15px;"> status: on <input type="radio" name="' + service.name + '_serviceStatus" value="on" ' + activeCheck + '> - off <input type="radio" name="' + service.name + '_serviceStatus" value="off" ' + notActiveCheck + '> <br><br>Results are deemed notable (capitilizes badge letter) if:';
                if (service.name === 'gnews') {
                  console.log(" if service.name == 'gnews'  servicesHtml ");
                  console.debug(service);
                  servicesHtml += '<br><br> the topic has had <input id="' + service.name + '_numberOfStoriesFoundWithinTheHoursSincePostedLimit" type="text" size="4" value="' + service.notableConditions.numberOfStoriesFoundWithinTheHoursSincePostedLimit + '"/> or more related stories published within the last <input id="' + service.name + '_hoursNotable" type="text" size="4" value="' + service.notableConditions.hoursSincePosted + '"/> hours <br> <div style="width:100%; text-align:center;"><span style="padding:7px; margin-right: 280px; display: inline-block;"> - or - </span></div> number of News Clusters  <input id="' + service.name + '_numberOfRelatedItemsWithClusterURL" type="text" size="4" value="' + service.notableConditions.numberOfRelatedItemsWithClusterURL + '"/> </div> </td> </tr></tbody></table> </div>';
                  console.log('trying to set with ' + service.notableConditions.hoursSincePosted + '"/> or fewer hours since posting - or');
                } else {
                  servicesHtml += '<br> URL is an exact match, and: <br> it has been <input id="' + service.name + '_hoursNotable" type="text" size="4" value="' + service.notableConditions.hoursSincePosted + '"/> or fewer hours since posting <br> <div style="width:100%; text-align:center;"><span style="padding:7px; margin-right: 280px; display: inline-block;"> - or - </span></div> a post has <input id="' + service.name + '_commentsNotable" type="text" size="4" value="' + service.notableConditions.num_comments + '"/> or more comments </div> </td> </tr></tbody></table> </div>';
                  console.log('trying to set with ' + service.notableConditions.hoursSincePosted + '"/> or fewer hours since posting - or');
                }
              }
              servicesHtml += "<div class='serviceListing listing' style='padding:15px; margin-top: 30px;'> Wouldn't it be awesome if we could add some more services to opt-in to?&nbsp;&nbsp; All that's needed are friendly APIs!&nbsp; <a href='https://twitter.com/spencenow' target='_blank'>Tweet me</a> if you're interested in adding one! </div>";
              return $("#servicesInfoDrop").html(servicesHtml);
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              var allInputs, autoTimerRadios, downButton, index, postError, saveButtons, service, upButton, _bindDown, _bindUp, _i, _len, _ref;
              saveButtons = $(_this.DOMselector + " .userPreferencesSave");
              saveButtons.attr('disabled', 'disabled');
              autoTimerRadios = $(_this.DOMselector + " input:radio[name='researchAutoOffType']");
              allInputs = $(_this.DOMselector + ' input');
              _this.elsToUnbind = _this.elsToUnbind.concat(allInputs, saveButtons, autoTimerRadios);
              allInputs.bind('change', function() {
                return $(".userPreferencesSave").removeAttr('disabled');
              });
              allInputs.bind('focus', function() {
                return $(".userPreferencesSave").removeAttr('disabled');
              });
              if ($("input:radio[name='researchAutoOffType']:checked").val() === 'custom') {
                $("#autoCustomValue").removeAttr('disabled');
              }
              autoTimerRadios.bind('change', function() {
                if ($("input:radio[name='researchAutoOffType']:checked").val() === 'custom') {
                  return $("#autoCustomValue").removeAttr('disabled');
                } else {
                  return $("#autoCustomValue").attr('disabled', 'disabled');
                }
              });
              _bindDown = function(downButton, index) {
                return downButton.bind('click', function() {
                  var parcel;
                  popupParcel.kiwi_servicesInfo = moveArrayElement(popupParcel.kiwi_servicesInfo, index, index + 1);
                  parcel = {
                    refreshView: 'userPreferences',
                    keyName: 'kiwi_servicesInfo',
                    newValue: popupParcel.kiwi_servicesInfo,
                    localOrSync: 'sync',
                    msg: 'kiwiPP_post_save_a_la_carte'
                  };
                  return sendParcel(parcel);
                });
              };
              _bindUp = function(upButton, index) {
                return upButton.bind('click', function() {
                  var parcel;
                  popupParcel.kiwi_servicesInfo = moveArrayElement(popupParcel.kiwi_servicesInfo, index, index - 1);
                  parcel = {
                    refreshView: 'userPreferences',
                    keyName: 'kiwi_servicesInfo',
                    newValue: popupParcel.kiwi_servicesInfo,
                    localOrSync: 'sync',
                    msg: 'kiwiPP_post_save_a_la_carte'
                  };
                  return sendParcel(parcel);
                });
              };
              _ref = popupParcel.kiwi_servicesInfo;
              for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
                service = _ref[index];
                downButton = $("#" + service.name + '_moveServiceDown');
                if (downButton.length > 0) {
                  _this.elsToUnbind.push(downButton);
                  _bindDown(downButton, index);
                }
                upButton = $("#" + service.name + '_moveServiceUp');
                if (upButton.length > 0) {
                  _this.elsToUnbind.push(upButton);
                  _bindUp(upButton, index);
                }
              }
              postError = function(userErrMsg) {
                console.log('trying to post error ' + userErrMsg);
                return $(_this.DOMselector + " .userErrMsg").html("<br>" + userErrMsg);
              };
              return saveButtons.bind('click', function() {
                var active, allowedAutoOffTypes, autoOffTimerType, autoOffTimerValue, hoursSincePosted, num_comments, numberOfRelatedItemsWithClusterURL, numberOfStoriesFoundWithinTheHoursSincePostedLimit, parcel, researchModeHTMLval, _j, _k, _len1, _len2, _ref1, _ref2;
                researchModeHTMLval = $("input:radio[name='research']:checked").val();
                console.log('researchModeHTMLval is ' + researchModeHTMLval);
                if (researchModeHTMLval !== 'on' && researchModeHTMLval !== 'off') {
                  postError('research mode must be "on" or "off"');
                  return 0;
                }
                allowedAutoOffTypes = ["20", "60", "always", "custom"];
                autoOffTimerType = $("input:radio[name='researchAutoOffType']:checked").val();
                autoOffTimerValue = $("#autoCustomValue").val();
                if (__indexOf.call(allowedAutoOffTypes, autoOffTimerType) >= 0) {
                  if (autoOffTimerType === 'custom' && (autoOffTimerValue === '' || isNaN(autoOffTimerValue))) {
                    postError('Must specify a number of minutes for auto-off timer.');
                    return 0;
                  }
                } else {
                  postError('not acceptable autoOffTimerType');
                  return 0;
                }
                _ref1 = popupParcel.kiwi_servicesInfo;
                for (index = _j = 0, _len1 = _ref1.length; _j < _len1; index = ++_j) {
                  service = _ref1[index];
                  if (service.name === 'gnews') {
                    active = $("input:radio[name='" + service.name + "_serviceStatus']:checked").val();
                    if (active !== 'on' && active !== 'off') {
                      postError('active must be "on" or "off"');
                      return 0;
                    }
                    numberOfStoriesFoundWithinTheHoursSincePostedLimit = $('#' + service.name + '_numberOfStoriesFoundWithinTheHoursSincePostedLimit').val();
                    if (numberOfStoriesFoundWithinTheHoursSincePostedLimit === '' || isNaN(numberOfStoriesFoundWithinTheHoursSincePostedLimit)) {
                      postError('number Of Stories Found Within The Hours Since Posted Limit must be an integer');
                      return 0;
                    }
                    numberOfRelatedItemsWithClusterURL = $('#' + service.name + '_numberOfRelatedItemsWithClusterURL').val();
                    if (numberOfRelatedItemsWithClusterURL === '' || isNaN(numberOfRelatedItemsWithClusterURL)) {
                      postError('number Of Related Items With Cluster URL of comments must be an integer');
                      return 0;
                    }
                  } else {
                    active = $("input:radio[name='" + service.name + "_serviceStatus']:checked").val();
                    if (active !== 'on' && active !== 'off') {
                      postError('active must be "on" or "off"');
                      return 0;
                    }
                    hoursSincePosted = $('#' + service.name + '_hoursNotable').val();
                    if (hoursSincePosted === '' || isNaN(hoursSincePosted)) {
                      postError('Hours must be an number');
                      return 0;
                    }
                    num_comments = $('#' + service.name + '_commentsNotable').val();
                    if (num_comments === '' || isNaN(num_comments)) {
                      postError('Number of comments must be an integer');
                      return 0;
                    }
                  }
                }
                console.log('1234');
                popupParcel.kiwi_userPreferences.researchModeOnOff = researchModeHTMLval;
                if (autoOffTimerType !== 'custom') {
                  popupParcel.kiwi_userPreferences.autoOffTimerType = autoOffTimerType;
                } else {
                  popupParcel.kiwi_userPreferences.autoOffTimerType = autoOffTimerType;
                  popupParcel.kiwi_userPreferences.autoOffTimerValue = parseFloat(autoOffTimerValue);
                }
                _ref2 = popupParcel.kiwi_servicesInfo;
                for (index = _k = 0, _len2 = _ref2.length; _k < _len2; index = ++_k) {
                  service = _ref2[index];
                  active = $("input:radio[name='" + service.name + "_serviceStatus']:checked").val();
                  popupParcel.kiwi_servicesInfo[index].active = active;
                  hoursSincePosted = $('#' + service.name + '_hoursNotable').val();
                  console.log(popupParcel.kiwi_servicesInfo[index].name);
                  console.log("hoursSincePosted = $('#' + service.name + '_hoursNotable').val() " + hoursSincePosted);
                  popupParcel.kiwi_servicesInfo[index].notableConditions.hoursSincePosted = parseFloat(hoursSincePosted);
                  if (service.name === 'gnews') {
                    numberOfRelatedItemsWithClusterURL = $('#' + service.name + '_numberOfRelatedItemsWithClusterURL').val();
                    popupParcel.kiwi_servicesInfo[index].notableConditions.numberOfRelatedItemsWithClusterURL = parseInt(numberOfRelatedItemsWithClusterURL);
                    numberOfStoriesFoundWithinTheHoursSincePostedLimit = $('#' + service.name + '_numberOfStoriesFoundWithinTheHoursSincePostedLimit').val();
                    popupParcel.kiwi_servicesInfo[index].notableConditions.numberOfStoriesFoundWithinTheHoursSincePostedLimit = parseInt(numberOfStoriesFoundWithinTheHoursSincePostedLimit);
                  } else {
                    num_comments = $('#' + service.name + '_commentsNotable').val();
                    popupParcel.kiwi_servicesInfo[index].notableConditions.num_comments = parseInt(num_comments);
                  }
                }
                popupParcel.view = 'userPreferences';
                console.log('4567');
                console.debug(popupParcel);
                parcel = {
                  refreshView: popupParcel.view,
                  newPopupParcel: popupParcel,
                  msg: 'kiwiPP_post_savePopupParcel'
                };
                return sendParcel(parcel);
              });
            };
          })(this)
        }
      };
    };

    return UserPreferences;

  })(SwitchView);

  Credits = (function(_super) {
    __extends(Credits, _super);

    function Credits(_at_name) {
      this.name = _at_name;
      this.__renderStates__ = __bind(this.__renderStates__, this);
      Credits.__super__.constructor.call(this, this.name, this.__renderStates__);
    }

    Credits.prototype.init = function(popupParcel) {
      this.unbindWidget();
      return this.render(popupParcel);
    };

    Credits.prototype.__renderStates__ = function() {
      return {
        __normal__: {
          paint: (function(_this) {
            return function(popupParcel) {
              return console.log('painting ' + _this.name);
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              return console.log('binding ' + _this.name);
            };
          })(this)
        }
      };
    };

    return Credits;

  })(SwitchView);

  Loading = (function(_super) {
    __extends(Loading, _super);

    function Loading(_at_name) {
      this.name = _at_name;
      this.__renderStates__ = __bind(this.__renderStates__, this);
      Loading.__super__.constructor.call(this, this.name, this.__renderStates__);
    }

    Loading.prototype.init = function(popupParcel) {
      this.unbindWidget();
      return this.render(popupParcel);
    };

    Loading.prototype.__renderStates__ = function() {
      return {
        __normal__: {
          paint: (function(_this) {
            return function(popupParcel) {
              return console.log('painting ' + _this.name);
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              return console.log('binding ' + _this.name);
            };
          })(this)
        }
      };
    };

    return Loading;

  })(SwitchView);

  KiwiSlice = (function(_super) {
    __extends(KiwiSlice, _super);

    function KiwiSlice(_at_name, uniqueSelectorPostfix) {
      this.name = _at_name;
      this.__renderStateTransitions__ = __bind(this.__renderStateTransitions__, this);
      this.__renderStates__ = __bind(this.__renderStates__, this);
      this.render = __bind(this.render, this);
      this.init = __bind(this.init, this);
      KiwiSlice.__super__.constructor.call(this, this.name, this.__renderStates__, uniqueSelectorPostfix);
    }

    KiwiSlice.prototype.init = function(popupParcel, renderState) {
      if (renderState == null) {
        renderState = null;
      }
      this.renderStateTransitions = this.__renderStateTransitions__();
      console.log('hehehehee init: (popupParcel, renderState = null) =>');
      this.unbindView();
      renderState = renderState != null ? renderstate : "collapsed";
      console.log(' renderState = if renderState? then renderstate else "collapsed" ' + renderState);
      return this.render(popupParcel, 'collapsed');
    };

    KiwiSlice.prototype.render = function(popupParcel, renderState, fromState) {
      var __renderStates__callback;
      if (fromState == null) {
        fromState = null;
      }
      console.log('in render for kiwi');
      __renderStates__callback = (function(_this) {
        return function(popupParcel, renderState) {
          return KiwiSlice.__super__.render.call(_this, popupParcel, renderState);
        };
      })(this);
      if ((fromState != null) && (this.renderStateTransitions[fromState + "__to__" + renderState] != null)) {
        console.log('yep, has renderstate');
        return this.renderStateTransitions[fromState + "__to__" + renderState](popupParcel, renderState, __renderStates__callback);
      } else {
        return KiwiSlice.__super__.render.call(this, popupParcel, renderState);
      }
    };

    KiwiSlice.prototype.__renderStates__ = function() {
      return {
        collapsed: {
          paint: (function(_this) {
            return function(popupParcel) {
              var kiwiSliceHTML;
              kiwiSliceHTML = '<div id="sliceActivateTransition" style="position:fixed; bottom: -33px; right: -33px; "> <img style="width: 66px; height: 66px;" src="symmetricKiwi.png" /> </div>';
              return $(_this.DOMselector).html(kiwiSliceHTML);
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              var elActivateTransition;
              elActivateTransition = $(_this.DOMselector + " #sliceActivateTransition");
              _this.elsToUnbind = _this.elsToUnbind.concat(elActivateTransition);
              elActivateTransition.bind('mouseover', function(ev) {
                return elActivateTransition.addClass('rotateClockwiseFull');
              });
              elActivateTransition.bind('mouseout', function(ev) {
                return elActivateTransition.removeClass('rotateClockwiseFull');
              });
              return elActivateTransition.bind('click', function(ev) {
                elActivateTransition.removeClass('rotateClockwiseFull');
                return _this.render(popupParcel, 'open', 'collapsed');
              });
            };
          })(this)
        },
        open: {
          paint: (function(_this) {
            return function(popupParcel) {
              var kiwiSliceHTML;
              console.log('painting ' + _this.name);
              kiwiSliceHTML = '<div id="transition_open_showMe" class="evenlySpacedContainer kiwiSliceOpenPlatter"> <button type="button" class=" goTo_creditsView btn btn-mini btn-default">credits</button> <button class=" btn btn-mini btn-default" style="" class="">MetaFruit <span class="glyphicon glyphicon-apple"></span></button> <button class=" btn btn-mini btn-default" id="clearKiwiURLCache">clear cache</button> <button class=" btn btn-mini btn-default" id="refreshURLresults">refresh</button> </div> <div id="sliceActivateTransition" style="position:fixed; bottom: 15px; right: 15px; "> <img style="width: 66px; height: 66px;" src="symmetricKiwi.png" /> </div>';
              $(_this.DOMselector).html(kiwiSliceHTML);
              return console.log(kiwiSliceHTML);
            };
          })(this),
          bind: (function(_this) {
            return function(popupParcel) {
              var clearKiwiURLCacheButton, elActivateTransition, refreshURLresultsButton;
              console.log('binding ' + _this.name);
              elActivateTransition = $(_this.DOMselector + " #sliceActivateTransition");
              clearKiwiURLCacheButton = $(_this.DOMselector + " #clearKiwiURLCache");
              refreshURLresultsButton = $(_this.DOMselector + " #refreshURLresults");
              _this.elsToUnbind = _this.elsToUnbind.concat(elActivateTransition, refreshURLresultsButton, clearKiwiURLCacheButton);
              refreshURLresultsButton.bind('click', function() {
                var parcel;
                parcel = {
                  msg: 'kiwiPP_refreshURLresults'
                };
                return sendParcel(parcel);
              });
              $('body').mouseup(function(e) {
                var container;
                console.log('test test test');
                container = $(_this.DOMselector);
                if (!container.is(e.target) && container.has(e.target).length === 0) {
                  $('body').unbind('mouseup');
                  return _this.render(popupParcel, 'collapsed', 'open');
                }
              });
              elActivateTransition.bind('click', function(ev) {
                return _this.render(popupParcel, 'collapsed', 'open');
              });
              return clearKiwiURLCacheButton.bind('click', function() {
                var parcel;
                parcel = {
                  msg: 'kiwiPP_clearAllURLresults'
                };
                return sendParcel(parcel);
              });
            };
          })(this)
        }
      };
    };

    KiwiSlice.prototype.__renderStateTransitions__ = function() {
      return {
        'open__to__collapsed': (function(_this) {
          return function(popupParcel, renderState, __renderStates__callback) {
            $(_this.DOMselector + " #transition_open_showMe").animate({
              'opacity': 0
            }, 300);
            $(_this.DOMselector + " #sliceActivateTransition").addClass('rotateClockwise');
            return $(_this.DOMselector + " #sliceActivateTransition").animate({
              "bottom": '-33px',
              "right": "-33px"
            }, {
              duration: 500,
              complete: function() {
                return __renderStates__callback(popupParcel, renderState);
              }
            });
          };
        })(this),
        'collapsed__to__open': (function(_this) {
          return function(popupParcel, renderState, __renderStates__callback) {
            console.log("'collapsed__to__open': (popupParcel, renderState, __renderStates__callback) =>");
            $(_this.DOMselector + " #sliceActivateTransition").addClass('rotateCounterClockwise');
            $(_this.DOMselector + " #sliceActivateTransition").animate({
              "bottom": '15px',
              "right": "15px"
            }, {
              duration: 500,
              complete: function() {
                console.log('we are done with animation');
                return __renderStates__callback(popupParcel, renderState);
              }
            });
            $(_this.DOMselector).prepend('<div id="transition_open_showMe" class="evenlySpacedContainer kiwiSliceOpenPlatter" style="opacity: 0;"> <button type="button" class="goTo_creditsView btn btn-mini btn-default ">credits</button> <button class="btn btn-mini btn-default " style="" class="">MetaFruit <span class="glyphicon glyphicon-apple"></span></button> <button class="btn btn-mini btn-default " id="clearKiwiURLCache">clear cache</button> <button class="btn btn-mini btn-default " id="refreshURLresults">refresh</button> </div>');
            return $(_this.DOMselector + " #transition_open_showMe").animate({
              'opacity': 1
            }, 499);
          };
        })(this)
      };
    };

    return KiwiSlice;

  })(FixedView);

  fixedViews = {
    kiwiSlice: new KiwiSlice('kiwiSlice', 'FixedBottom')
  };

  switchViews = {
    conversations: new Conversations('conversations'),
    userPreferences: new UserPreferences('userPreferences'),
    credits: new Credits('credits'),
    loading: new Loading('loading')
  };

  tailorResults = {
    gnews: function(serviceInfoObject, service_PreppedResults, kiwi_userPreferences) {
      var currentTime, index, listing, listingClass, preppedHTMLstring, recentTag, selectedString_attention, selectedString_recency, _i, _len, _time;
      currentTime = Date.now();
      preppedHTMLstring = "<div class='serviceResultsBox resultsBox__" + serviceInfoObject.name + "'> <div class='serviceResultsHeaderBar'> <span class='serviceResultsTitles'>" + serviceInfoObject.title + '</span> &nbsp;&nbsp;<a class="customSearchOpen"> modify search</a>';
      if (kiwi_userPreferences.sortByPref === 'attention') {
        selectedString_attention = 'selected';
        selectedString_recency = '';
      } else {
        selectedString_attention = '';
        selectedString_recency = 'selected';
      }
      preppedHTMLstring += '<div style="float:right; padding-top: 9px;">&nbsp;&nbsp; sorted by: <select class="conversations_sortByPref"> <option ' + selectedString_attention + ' id="_attention" value="attention">attention</option> <option ' + selectedString_recency + ' id="_recency" value="recency">recency</option> </select> </div> </div>';
      if ((service_PreppedResults != null) && service_PreppedResults.length > 0) {
        preppedHTMLstring += 'Searched for: "<strong>' + service_PreppedResults[0].kiwi_searchedFor + '</strong>"<br>';
      }
      if (kiwi_userPreferences.sortByPref === 'attention') {
        service_PreppedResults = _.sortBy(service_PreppedResults, 'clusterUrl');
        service_PreppedResults.reverse();
      } else if (kiwi_userPreferences.sortByPref === 'recency') {
        service_PreppedResults = _.sortBy(service_PreppedResults, 'kiwi_created_at');
        service_PreppedResults.reverse();
      }
      console.log('if kiwi_userPreferences.sortByPref is ');
      console.log(kiwi_userPreferences.sortByPref);
      console.log('console.debug serviceResults.service_PreppedResults');
      console.debug(service_PreppedResults);
      for (index = _i = 0, _len = service_PreppedResults.length; _i < _len; index = ++_i) {
        listing = service_PreppedResults[index];
        listingClass = index > 10 && service_PreppedResults.length > 14 ? ' hidden_listing' : '';
        recentTag = currentTime - listing.kiwi_created_at < 1000 * 60 * 60 * 4 ? "<span class='recentListingTag'>Recent: </span>" : "";
        preppedHTMLstring += '<div class="listing ' + listingClass + '" style="position:relative;">' + recentTag + '<a class="listingTitle" target="_blank" href="' + listing.unescapedUrl + '">' + listing.titleNoFormatting + '<br>';
        _time = formatTime(listing.kiwi_created_at);
        preppedHTMLstring += listing.publisher + ' -- ' + _time + '</a> <br>' + listing.content + '<br>';
        if (listing.clusterUrl !== '') {
          preppedHTMLstring += '<a target="_blank" href="' + listing.clusterUrl + '"> Google News cluster </a>';
        }
        preppedHTMLstring += '</a> </div>';
      }
      preppedHTMLstring += "</div>";
      return preppedHTMLstring;
    },
    hackerNews: function(serviceInfoObject, service_PreppedResults, kiwi_userPreferences) {
      return tailorRedditAndHNresults_returnHtml(serviceInfoObject, service_PreppedResults, kiwi_userPreferences);
    },
    reddit: function(serviceInfoObject, service_PreppedResults, kiwi_userPreferences) {
      return tailorRedditAndHNresults_returnHtml(serviceInfoObject, service_PreppedResults, kiwi_userPreferences);
    }
  };

  _tailorHNcomment = function(listing, serviceInfoObject, listingClass) {
    var commentHtml, currentTime, recentTag, _time;
    currentTime = Date.now();
    commentHtml = "";
    recentTag = currentTime - listing.kiwi_created_at < 1000 * 60 * 60 * 4 ? "<span class='recentListingTag'>Recent: </span>" : "";
    commentHtml += '<div class="listing ' + listingClass + ' " style="position:relative;">' + recentTag;
    if ((listing.over_18 != null) && listing.over_18 === true) {
      commentHtml += '<span class="nsfw">NSFW</span>For story: ' + listing.story_title + '<br>';
    } else {
      commentHtml += "For story: <a target='_blank' href='" + serviceInfoObject.permalinkBase + listing.story_id + "'>" + listing.story_title + '</a><br>';
    }
    _time = formatTime(listing.kiwi_created_at);
    commentHtml += 'at ' + _time + ', <a target="_blank" href="' + serviceInfoObject.userPageBaselink + listing.author + '">' + listing.author + '</a> recieved ' + listing.kiwi_score + ' upvotes, by saying: ( <a class="listingTitle" target="_blank" href="' + serviceInfoObject.permalinkBase + listing.kiwi_permaId + '"> comment permalink </a> , <a class="listingTitle" target="_blank" href="' + serviceInfoObject.permalinkBase + listing.story_id + '"> story permalink </a> )<br><div class="commentBox">' + listing.comment_text + '</div></div>';
    return commentHtml;
  };

  tailorRedditAndHNresults_returnHtml = function(serviceInfoObject, service_PreppedResults, kiwi_userPreferences) {
    var currentTime, fuzzyMatchBool, index, listing, listingClass, numberOfExactMatches, preppedHTMLstring, recentTag, selectedString_attention, selectedString_recency, _i, _j, _len, _len1, _time;
    preppedHTMLstring = '';
    currentTime = Date.now();
    fuzzyMatchBool = false;
    preppedHTMLstring += "<div class='serviceResultsBox resultsBox__" + serviceInfoObject.name + "'> <div class='serviceResultsHeaderBar'> <span class='serviceResultsTitles'>" + serviceInfoObject.title + '</span>';
    if (kiwi_userPreferences.sortByPref === 'attention') {
      selectedString_attention = 'selected';
      selectedString_recency = '';
    } else {
      selectedString_attention = '';
      selectedString_recency = 'selected';
    }
    preppedHTMLstring += '<div style="float:right; padding-top: 9px;"> &nbsp;&nbsp sorted by: <select class="conversations_sortByPref"> <option ' + selectedString_attention + ' id="_attention" value="attention">attention</option> <option ' + selectedString_recency + ' id="_recency" value="recency">recency</option> </select></div> </div>';
    if (service_PreppedResults.length < 1) {
      preppedHTMLstring += ' no results <br>';
      return preppedHTMLstring;
    } else if ((service_PreppedResults[0].comment_text == null) && kiwi_userPreferences.sortByPref === 'attention') {
      service_PreppedResults = _.sortBy(service_PreppedResults, 'num_comments');
      service_PreppedResults.reverse();
    } else if (kiwi_userPreferences.sortByPref === 'attention') {
      service_PreppedResults = _.sortBy(service_PreppedResults, 'kiwi_score');
      service_PreppedResults.reverse();
    } else if (kiwi_userPreferences.sortByPref === 'recency') {
      service_PreppedResults = _.sortBy(service_PreppedResults, 'kiwi_created_at');
      service_PreppedResults.reverse();
    }
    for (index = _i = 0, _len = service_PreppedResults.length; _i < _len; index = ++_i) {
      listing = service_PreppedResults[index];
      listingClass = index > 10 && service_PreppedResults.length > 14 ? ' hidden_listing ' : '';
      if (listing.comment_text != null) {
        preppedHTMLstring += _tailorHNcomment(listing, serviceInfoObject, listingClass);
      } else {
        recentTag = currentTime - listing.kiwi_created_at < 1000 * 60 * 60 * 4 ? "<span class='recentListingTag'>Recent: </span>" : "";
        if (listing.kiwi_exact_match) {
          preppedHTMLstring += '<div class="listing ' + listingClass + '">';
          if (serviceInfoObject.name !== 'reddit') {
            preppedHTMLstring += '<div style="float:right;"> <a target="_blank" href="' + serviceInfoObject.userPageBaselink + listing.author + '"> by ' + listing.author + '</a> </div>';
          }
          preppedHTMLstring += '<a class="listingTitle" target="_blank" href="' + serviceInfoObject.permalinkBase + listing.kiwi_permaId + '"><span style="color:black;">' + recentTag;
          if ((listing.over_18 != null) && listing.over_18 === true) {
            preppedHTMLstring += '<span class="nsfw">NSFW</span>' + listing.title + '<br>';
          } else {
            preppedHTMLstring += listing.title + '<br>';
          }
          _time = formatTime(listing.kiwi_created_at);
          preppedHTMLstring += listing.num_comments + ' comments, ' + listing.kiwi_score + ' upvotes -- ' + _time + '</span></a>';
          if (listing.subreddit != null) {
            preppedHTMLstring += '<br><span> <a target="_blank" href="' + serviceInfoObject.permalinkBase + '/r/' + listing.subreddit + '"> subreddit: ' + listing.subreddit + '</a></span>';
          }
          preppedHTMLstring += '<br><br></div>';
        } else {
          fuzzyMatchBool = true;
        }
      }
    }
    if (fuzzyMatchBool) {
      numberOfExactMatches = _.reduce(service_PreppedResults, function(memo, obj) {
        if (obj.kiwi_exact_match) {
          memo++;
          return memo;
        } else {
          return memo;
        }
      });
      if ((service_PreppedResults.length - numberOfExactMatches) > 10 && service_PreppedResults.length > 14) {
        listingClass = ' hidden_listing ';
      } else {
        listingClass = '';
      }
      preppedHTMLstring += '<div class="showFuzzyMatches ' + listingClass + '" style="position:relative;"> fuzzy matches: <br></div> <span class="fuzzyMatches">';
      console.log('fuzzy matches 12312312 ' + serviceInfoObject.name);
      for (index = _j = 0, _len1 = service_PreppedResults.length; _j < _len1; index = ++_j) {
        listing = service_PreppedResults[index];
        listingClass = index > 10 && service_PreppedResults.length > 14 ? ' hidden_listing ' : '';
        if (!listing.kiwi_exact_match) {
          recentTag = currentTime - listing.kiwi_created_at < 1000 * 60 * 60 * 4 ? "<span class='recentListingTag'>Recent: </span>" : "";
          preppedHTMLstring += '<div class="listing ' + listingClass + '">';
          if (serviceInfoObject.name !== 'reddit') {
            preppedHTMLstring += '<div style="float:right;"> <a target="_blank" href="' + serviceInfoObject.userPageBaselink + listing.author + '"> by ' + listing.author + '</a> </div>';
          }
          preppedHTMLstring += '<a class="listingTitle" target="_blank" href="' + serviceInfoObject.permalinkBase + listing.kiwi_permaId + '"><span style="color:black;">' + recentTag;
          if ((listing.over_18 != null) && listing.over_18 === true) {
            preppedHTMLstring += '<span class="nsfw">NSFW</span>' + listing.title + '<br>';
          } else {
            preppedHTMLstring += listing.title + '<br>';
          }
          preppedHTMLstring += listing.num_comments + ' comments, ' + listing.kiwi_score + ' upvotes ' + formatTime(listing.kiwi_created_at) + '</span> <br> for Url: <span class="altURL">' + listing.url + '</span> </a>';
          if (listing.subreddit != null) {
            preppedHTMLstring += '<br><span> <a target="_blank" href="' + serviceInfoObject.permalinkBase + '/r/' + listing.subreddit + '"> subreddit: ' + listing.subreddit + '</a></span> <div style="float:right;"> <a target="_blank" href="' + serviceInfoObject.userPageBaselink + listing.author + '"> by ' + listing.author + '</a></div>';
          }
          preppedHTMLstring += '<br></div>';
        }
      }
      preppedHTMLstring += "</span>";
    }
    preppedHTMLstring += "</div>";
    return preppedHTMLstring;
  };

  bindGoToViewButtons = function(buttonEls, viewName, viewData) {
    var el, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = buttonEls.length; _i < _len; _i++) {
      el = buttonEls[_i];
      _results.push($(el).bind('click', function(ev) {
        console.log('clicked ' + viewName);
        return switchViews[viewName].render(viewData);
      }));
    }
    return _results;
  };

  receiveParcel = function(parcel) {
    if (parcel.msg == null) {
      return false;
    }
    switch (parcel.msg) {
      case 'kiwiPP_popupParcel_ready':
        return chrome.tabs.query({
          currentWindow: true,
          active: true
        }, function(tabs) {
          var tabUrl;
          if (tabs.length > 0 && tabs[0].status === "complete") {
            if (tabs[0].url.indexOf('chrome-devtools://') !== 0) {
              tabUrl = tabs[0].url;
              if (tabs[0].url === parcel.forUrl) {
                console.log("when 'popupParcel_ready' parcel");
                console.debug(parcel);
                return initialize(parcel.popupParcel);
              }
            } else {
              console.log('chrome-devtools:// ');
              return 0;
            }
          }
        });
    }
  };

  sendParcel = function(parcel) {
    var port;
    console.log('wtf sent');
    port = chrome.extension.connect({
      name: "kiwi_fromBackgroundToPopup"
    });
    return chrome.tabs.query({
      currentWindow: true,
      active: true
    }, function(tabs) {
      if (tabs.length > 0 && tabs[0].status === "complete") {
        if (tabs[0].url.indexOf('chrome-devtools://') !== 0) {
          parcel.forUrl = tabs[0].url;
          if (parcel.msg == null) {
            return false;
          }
          switch (parcel.msg) {
            case 'kiwiPP_refreshSearchQuery':
              return port.postMessage(parcel);
            case 'kiwiPP_post_customSearch':
              return port.postMessage(parcel);
            case 'kiwiPP_request_popupParcel':
              return port.postMessage(parcel);
            case 'kiwiPP_post_savePopupParcel':
              return port.postMessage(parcel);
            case 'kiwiPP_post_save_a_la_carte':
              return port.postMessage(parcel);
            case 'kiwiPP_clearAllURLresults':
              return port.postMessage(parcel);
            case 'kiwiPP_refreshURLresults':
              return port.postMessage(parcel);
            case 'kiwiPP_researchUrlOverrideButton':
              return port.postMessage(parcel);
          }
        } else {
          console.log('chrome-devtools:// ');
          return 0;
        }
      }
    });
  };

  chrome.extension.onConnect.addListener(function(port) {
    if (port.name === 'kiwi_fromBackgroundToPopup') {
      return port.onMessage.addListener(function(pkg) {
        return receiveParcel(pkg);
      });
    }
  });

  moveArrayElement = function(array, from, to) {
    array.splice(to, 0, array.splice(from, 1)[0]);
    return array;
  };

  getRandom = function(min, max) {
    return min + Math.floor(Math.random() * (max - min + 1));
  };

  formatTime = function(utcMillisecondTimestamp) {
    var a, amOrPm, date, hour, min, month, months, sec, time, year;
    a = new Date(utcMillisecondTimestamp);
    months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    year = a.getFullYear();
    month = months[a.getMonth()];
    date = a.getDate();
    hour = a.getHours();
    min = a.getMinutes();
    sec = a.getSeconds();
    amOrPm = hour > 11 ? 'pm' : 'am';
    if (hour > 12) {
      hour = hour - 12;
    } else if (parseInt(hour) === 0) {
      hour = 12;
    }
    if (min < 10) {
      min = '0' + min;
    }
    time = month + ' ' + date + ', ' + year + ' - ' + hour + ':' + min + amOrPm;
    return time;
  };

  renderExtensionHeight = function(elementSelector, extraPx) {
    var extHeight_;
    if (viewElementId === elementSelector) {
      extraPx = 2;
      extHeight_ = $(elementSelector).outerHeight() + extraPx;
      if (extHeight_ > 590) {
        extHeight_ = 590;
      }
      $('body').css('height', extHeight_ + 'px');
      heightString = extHeight_.toString() +'px';
      $('html').css('min-height', heightString);
      extHeight_--;
      return $('body').css('min-height', heightString);
    }
  };

  capitalizeFirstLetter = function(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  };

  htmlEntities = function(str) {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };

  getURLParam = function(oTarget, sVar) {
    return decodeURI(oTarget.search.replace(new RegExp("^(?:.*[&\\?]" + encodeURI(sVar).replace(/[\.\+\*]/g, "\\$&") + "(?:\\=([^&]*))?)?.*$", "i"), "$1"));
  };

  console.log('trying to send123');

  $().ready(sendParcel({
    'msg': 'kiwiPP_request_popupParcel'
  }));

}).call(this);
